apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: mern-stack
spec:
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      initContainers:
      - name: wait-for-mongodb
        image: busybox
        command: ['sh', '-c', 'until nc -z mongodb-service 27017; do echo waiting for mongodb; sleep 2; done;']
      containers:
      - name: backend
        image: mern-backend:v1
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "200m"
            memory: "256Mi"
        envFrom:
        - secretRef:
            name: backend-secret
        volumeMounts:
        - name: logs
          mountPath: /var/log
      - name: sidecar
        image: busybox
        command: ["/bin/sh"]
        args: ["-c", "tail -f /var/log/backend.log"]
        volumeMounts:
        - name: logs
          mountPath: /var/log
      volumes:
      - name: logs
        emptyDir: {} 