name: MERN Stack CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  DOCKER_FRONTEND_IMAGE: faheempechuho56/mern-frontend
  DOCKER_BACKEND_IMAGE: faheempechuho56/mern-backend
  DOCKER_REGISTRY: docker.io

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Install Frontend Dependencies
      working-directory: mern-app/frontend
      run: |
        npm install
        npm run build
      
    - name: Test Frontend
      working-directory: mern-app/frontend
      run: |
        echo "No tests configured - skipping frontend tests"
        exit 0
      
    - name: Install Backend Dependencies
      working-directory: mern-app/backend
      run: npm install
      
    - name: Test Backend
      working-directory: mern-app/backend
      run: |
        echo "No tests configured - skipping backend tests"
        exit 0

  docker-build-and-push:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
        
    - name: Build and push Frontend Docker image
      uses: docker/build-push-action@v4
      with:
        context: ./mern-app/frontend
        push: true
        tags: ${{ env.DOCKER_FRONTEND_IMAGE }}:${{ github.sha }},${{ env.DOCKER_FRONTEND_IMAGE }}:latest
        
    - name: Build and push Backend Docker image
      uses: docker/build-push-action@v4
      with:
        context: ./mern-app/backend
        push: true
        tags: ${{ env.DOCKER_BACKEND_IMAGE }}:${{ github.sha }},${{ env.DOCKER_BACKEND_IMAGE }}:latest

  deploy:
    needs: docker-build-and-push
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up kubectl
      uses: azure/setup-kubectl@v3
      
    - name: Configure kubectl
      run: |
        echo "${{ secrets.KUBE_CONFIG }}" > kubeconfig.yaml
        export KUBECONFIG=kubeconfig.yaml
        
    - name: Update Kubernetes manifests
      run: |
        cd k8s
        # Update image tags in deployments
        sed -i "s|image: .*mern-frontend.*|image: ${{ env.DOCKER_FRONTEND_IMAGE }}:${{ github.sha }}|" frontend/deployment.yaml
        sed -i "s|image: .*mern-backend.*|image: ${{ env.DOCKER_BACKEND_IMAGE }}:${{ github.sha }}|" backend/deployment.yaml
        
    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f k8s/namespace.yaml
        kubectl apply -f k8s/mongodb/
        kubectl apply -f k8s/backend/
        kubectl apply -f k8s/frontend/
        kubectl rollout status deployment/frontend-deployment -n mern-stack
        kubectl rollout status deployment/backend-deployment -n mern-stack 